apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: a4kr6x4hi-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a4kr6x4hi-nodejs 
  name: a4kr6x4hi-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: a4kr6x4hi-nodejs 
